SkillsShopify/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include( ('shopifyapp.urls' , 'shopifyapp') , namespace="shopify"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopifyapp/urls.py
from django.urls import path
from shopifyapp.views import IndexPageView, CreateProductView, CreateCategoryView , ViewProduct , EditProduct , DeleteProduct , SearchProduct

urlpatterns = [
    path(''   , IndexPageView.as_view() , name="home"),
    path('create-product/' , CreateProductView.as_view() , name="create-product"),
    path('create-category/' , CreateCategoryView.as_view() , name="create-category"),
    path('view-product/<int:id>/' , ViewProduct.as_view() ,name="view-product"),
    path('edit-product/<int:id>/' , EditProduct.as_view() ,name="edit-product"),
    path('delete-product/<int:id>/' , DeleteProduct.as_view() ,name="delete-product"),
    path('search-product/' , SearchProduct.as_view() ,name="search-product"),
]

shopifyapp/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=50)
    discription = models.TextField()
    original_price = models.FloatField()
    discount_percentage = models.IntegerField()
    selling_price = models.FloatField()
    image = models.ImageField(upload_to='media')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.name

userapp/models.py
from django.db import models



shopifyapp/views.py
from django.shortcuts import render , redirect
from django.views import View
from shopifyapp.models import Category, Product 
from django.db.models import Q


class IndexPageView(View):
    def get(self, request):
        products = Product.objects.exclude(image='').order_by('-id')[:3]

        return render (request, 'shopifyapp/index.html', context={'products' : products})
    
class CreateProductView(View):
    flag = False
    
    def get(self, request):
        all_category = Category.objects.all()
        return render (request, 'shopifyapp/add-product.html', {'category' : all_category })
    
    def post(self, request) :
        flag = False
        try :
            category_id = request.POST.get('category')
            obj = Category.objects.get(pk=category_id)



            original_price_user = eval (request.POST.get("oprice") )
            discount_percentage_user = eval (request.POST.get("dprice"))
            discount_price = original_price_user * discount_percentage_user / 100
            selling_price = original_price_user - discount_price

            Product.objects.create(
                name = request.POST.get("pname") ,
                discription = request.POST.get("discription") ,
                original_price = original_price_user ,
                discount_percentage = discount_percentage_user ,
                selling_price = selling_price ,
                image = request.FILES.get("image") ,
                category = obj , 
            )
            return redirect('shopify:home')
        except Exception as e :
            flag = False
            print(f'{type (e).__name__} : {e}')

        return render(request , 'shopifyapp/add-product.html' , {'flag' : flag})
    
class CreateCategoryView(View):
    flag = False 
    def get(self, request) :
        return render(request , 'shopifyapp/add-category.html')
    
    def post(self, request) :
        flag = False
        try :
            category_name = request.POST.get('cname')
            category = Category(name=category_name)
            category.save()

            print("Product Added successfully")
            flag = True
            return redirect('shopify:home')
        except Exception as e :
            flag = False
            print(f'{type (e).__name__} : {e}')

        return render(request , 'shopifyapp/add-category.html' , {'flag' : flag})
    
    
class ViewProduct(View):

    def get(self, request , id):
        print(id)
        product = Product.objects.get(pk=id)
        return render(request , 'shopifyapp/view-product.html',{"product":product})
     
class EditProduct(View):

    def get(self, request , id):
        product = Product.objects.get(pk=id)
        return render(request , 'shopifyapp/edit-product.html',{"product":product})
    
    def post(self, request,id):
        try:
            db_product = Product.objects.get(pk=id)

            original_price_user = eval(request.POST.get("oprice"))
            discount_percentage_user = eval(request.POST.get("dprice"))
            discount_price = original_price_user * discount_percentage_user / 100
            selling_price = original_price_user - discount_price

            db_product.name = request.POST.get("pname")
            db_product.discription = request.POST.get("discription")
            db_product.original_price = original_price_user
            db_product.discount_percentage = discount_percentage_user
            db_product.selling_price = selling_price

            if request.FILES.get("image"):
                db_product.image = request.FILES.get("image")

            db_product.save()
            print("Product updated successfully")
            return redirect('shopify:home')
        except Exception as e:
            print(f'{type(e).__name__} : {e}')
        return render(request, 'shopifyapp/add-product.html')



class DeleteProduct(View):
    def get(self, request , id):
        product = Product.objects.get(pk=id)
        product.delete()
        return redirect('shopify:home')
    
class SearchProduct(View):
    def post(self, request):
         
        search = request.POST.get("search")

        search_list = Product.objects.filter(Q(name__icontains = search) | Q(category__name = search))


        print( search_list)

        return render(request, "searchlist.html", {'search_list' : search_list})




userapp/views.py
from django.shortcuts import render

# Create your views here.

shopifyapp/templates/searchlist.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %} 

    <title> shopifyapp-search </title>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

{% endblock %}

{% block body %} 
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About shopifyapp</h4>
          <p class="text-muted"> Skills IT Academy created it's own shopping website for student to purchase java |  python | DS related stuff !!</p>
        
</header>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1>shopify</h1>
      <p class="lead text-muted">Skills IT Academy created it's own shopping website for student to purchase java |  python | DS related stuff !!</p>
        <a href="{% url 'shopify:create-product'%}" class="btn btn-primary my-2">Add Product</a>
        <a href="{% url 'shopify:create-category'%}" class="btn btn-secondary my-2">Add Product Category</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row justify-content-center">


        {% for product in search_list %}
       


        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top"   src="{{ product.image.url}}"   alt="Thumbnail"  width="100%"  height="225">

            <div class="card-body">
              <h3> {{ product.name }}</h3>
              
              <hr>
                    <p> Original Price ₹: {{ product.original_price }} </p>
                    <p style="color:red"> Discount Percentage : {{ product.discount_percentage }} %</p>
                    <p> <b> Selling Price ₹: {{ product.selling_price }} </b> </p>
                  
                  
               <hr>   
              <p class="card-text"> {{ product.discription }} </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'shopify:home' %}" class="btn btn-sm btn-outline-success">Back</a> &nbsp;
                  <a href="" class="btn btn-sm btn-outline-warning">Edit</a>  &nbsp;
                  <a href="#" class="btn btn-sm btn-outline-danger">Delete</a> &nbsp;
                </div>
                <small class="text-muted">9 mins</small>
              </div>
          </div>
        </div>
    </div>

    {% endfor %}
    
   </div>
</div>
  </div>
  

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>  ©SkillsITAcademy | shopifyapp | SanyuInfoTechPvtLtd </p>

  </div>
</footer>





{% endblock %}

shopifyapp/templates/shopifyapp/add-category.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %} 

    <title> shopifyapp-add-category</title>
{% endblock %}

{% block body %} 

<h1> Add category Here</h1>

{% if flag %}
    <p> category saved to DB </p>

{% endif %}

<form action="" method="POST"> {% csrf_token %}

  <div class="form-group">
    <label for="Name">Product Name</label>
    <input type="text" class="form-control" name="cname" aria-describedby="emailHelp">
  </div>

  

  <button type="submit" class="btn btn-primary">Add Product</button>
</form>

<!-- ✅ JavaScript to prevent form resubmission -->
<script>
    // This removes the form POST data from browser history
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>

{% endblock %}

shopifyapp/templates/shopifyapp/add-product.html
{% extends "shopifyapp/base.html" %}
{% load static %}

{%block head%}
<title>shopify-add-product</title>
{% endblock %}        


{%block body%} 

<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
  <a class="navbar-brand d-flex align-items-center" href="shopifyapp\templates\shopifyapp\index.html">
    <h1> Add Your Product Here </h1>
  </a>
</nav>
<br>
<!-- Navbar End -->

<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

  <div class="form-group">
    <label for="name"> Product Name</label>
    <input type="text" class="form-control" name = "pname"  aria-describedby="emailHelp">
  </div>

  <div class="form-group">
    <label for="Discription">Discription</label>
    <input type="text" class="form-control" name = "discription">
  </div>

  <div class="form-group">
    <label for="Discription">Original Price</label>
    <input type="integer" class="form-control" name = "oprice">
  </div>

  <div class="form-group">
    <label for="Discription">Discount Percentage</label>
    <input type="text" class="form-control" name = "dprice">
  </div>

  <div class="form-group">
    <label for="Discription">Image</label>
    <input type="file" class="form-control" name = "image">
  </div>
  
<div class="input-group mb-3">
  <div class="input-group-prepend">
    <label class="input-group-text" for="inputGroupSelect01">Category</label>
  </div>
  <select class="custom-select" name="category" id="inputGroupSelect01">
    
    <option selected>Choose...</option>
    {% for cat in category%}
    <option value="{{cat.id}}">{{cat.name}}</option>
    {% endfor %}
  </select>
</div>

  <button type="submit" class="btn btn-primary">Add Product</button>
</form>

{%endblock%}

shopifyapp/templates/shopifyapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    {% block head %} {% endblock %}
  </head>
  <body>
    <div class="container">
        {% include 'shopifyapp/navbar.html' %}
        {% block body %} {% endblock %}
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

shopifyapp/templates/shopifyapp/edit-product.html
{% extends "shopifyapp/base.html" %}
{% load static %}

{%block head%}
<title>shopify-edit-product</title>
{% endblock %}        


{%block body%} 

<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
  <a class="navbar-brand d-flex align-items-center" href="shopifyapp\templates\shopifyapp\index.html">
    <h1> Edit Your Product Here </h1>
  </a>
</nav>
<br>
<!-- Navbar End -->

<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

  <div class="form-group">
    <label for="name"> Product Name</label>
    <input type="text" class="form-control" value= "{{product.name}}" name = "pname"  aria-describedby="emailHelp">
  </div>

  <div class="form-group">
    <label for="Discription">Discription</label>
    <input type="text" class="form-control" value= "{{product.discription}}" name = "discription">
  </div>

  <div class="form-group">
    <label for="Discription">Original Price</label>
    <input type="integer" class="form-control" value= "{{product.original_price}}" name = "oprice">
  </div>

  <div class="form-group">
    <label for="Discription">Discount Percentage</label>
    <input type="text" class="form-control" value= "{{product.discount_percentage}}" name = "dprice">
  </div>

  <div class="form-group">
    <label for="Discription">Image</label>
    <input type="file" class="form-control" value= "{{product.image}}" name = "image">
  </div>
  


  <button type="submit" class="btn btn-primary">Edit Product</button>
</form>

{%endblock%}

shopifyapp/templates/shopifyapp/index.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %} 

    <title> shopifyapp-index </title>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

{% endblock %}

{% block body %} 
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About shopifyapp</h4>
          <p class="text-muted"> Skills IT Academy created it's own shopping website for student to purchase java |  python | DS related stuff !!</p>
        
</header>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1>shopify</h1>
      <p class="lead text-muted">Skills IT Academy created it's own shopping website for student to purchase java |  python | DS related stuff !!</p>
        <a href="{% url 'shopify:create-product'%}" class="btn btn-primary my-2">Add Product</a>
        <a href="{% url 'shopify:create-category'%}" class="btn btn-secondary my-2">Add Product Category</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row">

       {% for product in products|slice:":3" %}


        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top"   src="{{ product.image.url}}"   alt="Thumbnail"  width="100%"  height="225">

            <div class="card-body">
              <h3> {{ product.name }}</h3>
              <hr>
                    <p> Original Price ₹: {{ product.original_price }} </p>
                    <p style="color:red"> Discount Percentage : {{ product.discount_percentage }} %</p>
                    <p> <b> Selling Price ₹: {{ product.selling_price }} </b> </p>
                  
                  
               <hr>   
              <p class="card-text"> {{ product.discription | truncatechars:20 }} <a href= "{% url 'shopify:view-product' product.id%}">more</a></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'shopify:view-product' product.id%}" class="btn btn-sm btn-outline-success">View</a> &nbsp;
                  <a href="{% url 'shopify:edit-product' product.id%}" class="btn btn-sm btn-outline-warning">Edit</a>  &nbsp;
                  <a href="{% url 'shopify:delete-product' product.id%}" class="btn btn-sm btn-outline-danger">Delete</a> &nbsp;
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

        {% endfor %}

      </div>
   </div>
</div>
       
  

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>  ©SkillsITAcademy | shopifyapp | SanyuInfoTechPvtLtd </p>

  </div>
</footer>






{% endblock %}

shopifyapp/templates/shopifyapp/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">shopify</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Category
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Electronics</a>
          <a class="dropdown-item" href="#">Cloths</a>
          
        </div>
      </li>

       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ROLE
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">SELLER</a>
          <a class="dropdown-item" href="#">BUYER</a>
          
        </div>
      </li>
      
    </ul>
    <form action="{% url 'shopify:search-product' %}" class="form-inline my-2 my-lg-0" method="POST"> {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

shopifyapp/templates/shopifyapp/view-product.html
{% extends 'shopifyapp/base.html' %}
{% load static %}

{% block head %} 

    <title> shopifyapp-index </title>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

{% endblock %}

{% block body %} 
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About shopifyapp</h4>
          <p class="text-muted"> Skills IT Academy created it's own shopping website for student to purchase java |  python | DS related stuff !!</p>
        
</header>

<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <h1>shopify</h1>
      <p class="lead text-muted">Skills IT Academy created it's own shopping website for student to purchase java |  python | DS related stuff !!</p>
        <a href="{% url 'shopify:create-product'%}" class="btn btn-primary my-2">Add Product</a>
        <a href="{% url 'shopify:create-category'%}" class="btn btn-secondary my-2">Add Product Category</a>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row justify-content-center">

       


        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <img class="bd-placeholder-img card-img-top"   src="{{ product.image.url}}"   alt="Thumbnail"  width="100%"  height="225">

            <div class="card-body">
              <h3> {{ product.name }}</h3>
              
              <hr>
                    <p> Original Price ₹: {{ product.original_price }} </p>
                    <p style="color:red"> Discount Percentage : {{ product.discount_percentage }} %</p>
                    <p> <b> Selling Price ₹: {{ product.selling_price }} </b> </p>
                  
                  
               <hr>   
              <p class="card-text"> {{ product.discription }} </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'shopify:home'  %}" class="btn btn-sm btn-outline-success">Back</a> &nbsp;
                  <a href="{% url 'shopify:edit-product' product.id%}" class="btn btn-sm btn-outline-warning">Edit</a>  &nbsp;
                  <a href="#" class="btn btn-sm btn-outline-danger">Delete</a> &nbsp;
                </div>
                <small class="text-muted">9 mins</small>
              </div>
          </div>
        </div>

        
      </div>
   </div>
</div>
       
  

</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>  ©SkillsITAcademy | shopifyapp | SanyuInfoTechPvtLtd </p>

  </div>
</footer>





{% endblock %}